version: "3"
services:

  mongo:
    image: "mongo:5.0.8"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "27017:27017"
    logging:
      driver: none

  influx:
    image: "influxdb:1.8-alpine"
    ports:
      - "8086:8086"
    environment:
      "INFLUXDB_DB": "kre"
      "INFLUXDB_META_DIR": "/var/lib/influxdb/meta2"

  nats:
    image: "nats:2.8.1"
    command:
      - "-js"
    ports:
      - "4222:4222"
      - "8222:8222"

  node-py:
    build:
      context: "../../kre-py"
      dockerfile: "./Dockerfile"
    volumes:
      - "./nodeA-vol:/tmp"
    environment:
      "KRT_WORKFLOW_NAME": ${KRT_WORKFLOW_NAME}
      "KRT_VERSION_ID": ${KRT_VERSION_ID}
      "KRT_VERSION": ${KRT_VERSION}
      "KRT_NATS_SERVER": ${KRT_NATS_SERVER}
      "KRT_NATS_STREAM": ${KRT_NATS_STREAM}
      "KRT_NATS_MONGO_WRITER": ${KRT_NATS_MONGO_WRITER}
      "KRT_BASE_PATH": ${KRT_BASE_PATH}
      "KRT_MONGO_URI": ${KRT_MONGO_URI}
      "KRT_INFLUX_URI": ${KRT_INFLUX_URI}
      "KRT_NODE_NAME": ${NODEA_KRT_NODE_NAME}
      "KRT_NATS_INPUT": ${NODEA_KRT_NATS_INPUT}
      "KRT_NATS_OUTPUT": ${NODEA_KRT_NATS_OUTPUT}
      "KRT_NATS_ENTRYPOINT_SUBJECT": ${NODEA_KRT_NATS_ENTRYPOINT_SUBJECT}
      "KRT_HANDLER_PATH": ${NODEA_KRT_HANDLER_PATH}
      "KRT_IS_LAST_NODE": ${NODEA_KRT_IS_LAST_NODE}

  node-py-2:
    build:
      context: "../../kre-py"
      dockerfile: "./Dockerfile"
    volumes:
      - "./nodeB-vol:/tmp"
    environment:
      "KRT_WORKFLOW_NAME": ${KRT_WORKFLOW_NAME}
      "KRT_VERSION_ID": ${KRT_VERSION_ID}
      "KRT_VERSION": ${KRT_VERSION}
      "KRT_NATS_SERVER": ${KRT_NATS_SERVER}
      "KRT_NATS_STREAM": ${KRT_NATS_STREAM}
      "KRT_NATS_MONGO_WRITER": ${KRT_NATS_MONGO_WRITER}
      "KRT_BASE_PATH": ${KRT_BASE_PATH}
      "KRT_MONGO_URI": ${KRT_MONGO_URI}
      "KRT_INFLUX_URI": ${KRT_INFLUX_URI}
      "KRT_NODE_NAME": ${NODEB_KRT_NODE_NAME}
      "KRT_NATS_INPUT": ${NODEB_KRT_NATS_INPUT}
      "KRT_NATS_OUTPUT": ${NODEB_KRT_NATS_OUTPUT}
      "KRT_NATS_ENTRYPOINT_SUBJECT": ${NODEB_KRT_NATS_ENTRYPOINT_SUBJECT}
      "KRT_HANDLER_PATH": ${NODEB_KRT_HANDLER_PATH}
      "KRT_IS_LAST_NODE": ${NODEB_KRT_IS_LAST_NODE}
    logging:
      driver: none

  node-go-1:
    build:
      context: "../../kre-go"
      dockerfile: "./Dockerfile"
    volumes:
      - "./nodeC-vol:/tmp"
    environment:
      "KRT_WORKFLOW_NAME": ${KRT_WORKFLOW_NAME}
      "KRT_VERSION_ID": ${KRT_VERSION_ID}
      "KRT_VERSION": ${KRT_VERSION}
      "KRT_NATS_SERVER": ${KRT_NATS_SERVER}
      "KRT_NATS_STREAM": ${KRT_NATS_STREAM}
      "KRT_NATS_MONGO_WRITER": ${KRT_NATS_MONGO_WRITER}
      "KRT_BASE_PATH": ${KRT_BASE_PATH}
      "KRT_MONGO_URI": ${KRT_MONGO_URI}
      "KRT_INFLUX_URI": ${KRT_INFLUX_URI}
      "KRT_NODE_NAME": ${NODEC_KRT_NODE_NAME}
      "KRT_NATS_INPUT": ${NODEC_KRT_NATS_INPUT}
      "KRT_NATS_OUTPUT": ${NODEC_KRT_NATS_OUTPUT}
      "KRT_NATS_ENTRYPOINT_SUBJECT": ${NODEC_KRT_NATS_ENTRYPOINT_SUBJECT}
      "KRT_HANDLER_PATH": ${NODEC_KRT_HANDLER_PATH}
      "KRT_IS_LAST_NODE": ${NODEC_KRT_IS_LAST_NODE}
    logging:
      driver: none

  node-entrypoint:
    build:
      context: "../../kre-entrypoint"
      dockerfile: "./Dockerfile"
    volumes:
      - "./entrypoint-vol/src:/src"
      - "./entrypoint-vol/krt-files:/krt-files"
    ports:
      - "9000:9000"
    environment:
      #"KRT_WORKFLOW_NAME": ${KRT_WORKFLOW_NAME}
      "KRT_VERSION_ID": ${KRT_VERSION_ID}
      "KRT_VERSION": ${KRT_VERSION}
      "KRT_NODE_NAME": ${KRT_NODE_NAME}
      "KRT_NODE_ID": ${ENTRYPOINT_KRT_NODE_ID}
      "KRT_NATS_STREAM": ${KRT_NATS_STREAM}
      "KRT_NATS_SERVER": ${KRT_NATS_SERVER}
      "KRT_NATS_SUBJECTS_FILE": ${ENTRYPOINT_KRT_NATS_SUBJECTS_FILE}
      "KRT_INFLUX_URI": ${KRT_INFLUX_URI}
      "KRT_NATS_INPUT": ${ENTRYPOINT_KRT_NATS_INPUT}
      "KRT_NATS_OUTPUT": ${ENTRYPOINT_KRT_NATS_OUTPUT}
      "KRT_RUNTIME_ID": ${KRT_RUNTIME_ID}
      "KRT_NATS_SUBSCRIPTION_TIMEOUT": ${KRT_NATS_SUBSCRIPTION_TIMEOUT}
