version: "3"
services:
  nats:
    image: "nats-streaming:0.16.2"
    ports:
      - "4222:4222"
      - "8222:8222"
  mongo:
    image: "mongo:4.2"
    ports:
      - "27017:27017"
  influx:
    image: "influxdb:1.8-alpine"
    ports:
      - 8086:8086
  influx_init:
    image: "influxdb:1.8-alpine"
    environment:
      INFLUX_DATABASE: "kre"
    volumes: 
      - "./influx:/docker-entrypoint-initdb.d"
    command: /init-influxdb.sh
  runner:
    build:
      context: "../"
      dockerfile: "./Dockerfile"
      args:
        BUILD_ENV: "test"
    volumes:
      - "../test_assets:/tmp"
