name: kre-py Tests

on:
  push:
    branches:
      - "*"
    paths:
      - "kre-py/**/*"
      - ".github/workflows/kre-py*"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    services:
      influxdb: nats:2.1.6
        image: influxdb:1.7-alpine
      mongo:
        image: mongo:4.2
      nats:
        image: nats:2.1.6

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel

    - id: cache-pipenv
      uses: actions/cache@v1
      working-directory: ./kre-py
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}

    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install --deploy --dev

    - name: Test with pytest
      run: |
        pipenv run test -svvv
        touch coverage.out
      working-directory: ./kre-py

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: kre-py/coverage.out

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Download code coverage results
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
          path: kre-py
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: kre-py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_KRE_PY }}
