name: kre-py Semantic Release

on:
  workflow_run:
    workflows:
      - "kre-py Tests"
    branches: [ main ]
    types:
      - completed

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        working-directory: ./kre-entrypoint
        run: npm install
      - name: Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}
        working-directory: ./kre-entrypoint
        run: npx semantic-release --debug
      - name: Upload release_version
        uses: actions/upload-artifact@v2
        with:
          name: release_version
          path: kre-py/release_version.txt

  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: semantic-release

      - name: Download release_version
        uses: actions/download-artifact@v2
        with:
          name: release_version
          path: kre-py

      - name: Read release_version
        id: release_version
        run: |
          echo ::set-output name=RELEASE_VERSION::$(cat kre-py/release_version.txt)

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./kre-entrypoint
          file: ./kre-entrypoint/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            konstellation/kre-runtime-entrypoint:${{ steps.release_version.outputs.RELEASE_VERSION }}
            konstellation/kre-runtime-entrypoint:latest
