name: kre-py Semantic Release

on:
  workflow_run:
    workflows:
      - "kre-py Tests"
    branches: [ main ]
    types:
      - completed

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        working-directory: ./kre-py
        id: semantic_release
        with:
          branch: main
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
          extends: |
            semantic-release-monorepo
        env:
          GH_TOKEN: ${{ secrets.PATNAME }}

      - name: New release published for kre-py
        if: steps.semantic_release.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic_release.outputs.new_release_version }}
          echo ${{ steps.semantic_release.outputs.new_release_major_version }}
          echo ${{ steps.semantic_release.outputs.new_release_minor_version }}
          echo ${{ steps.semantic_release.outputs.new_release_patch_version }}
